# Generated by Django 4.2.4 on 2023-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('city', models.CharField(max_length=30, verbose_name='Город проживаиния')),
                ('job', models.CharField(max_length=30, verbose_name='Место работы')),
                ('date_of_birth', models.DateField(default='01.01.1990', verbose_name='Дата рождения')),
            ],
        ),
    ]
